export const CREATE_EVENT = "CREATE_EVENT";
export const DELEATE_EVENT = "DELEATE_EVENT";
export const DELEATE_ALL_EVENTS = "DELEATE_ALL_EVENTS";

export const ADD_OPERATION_LOG = "ADD_OPERATION_LOG";
export const DELETE_ALL_OPERATION_LOGS = "DELETE_ALL_OPERATION_LOGS";
